- name: Install libvirt related packages
  ansible.builtin.dnf:
    name:
      - libvirt-daemon-kvm
    state: latest

- name: Enable libvirt daemon
  service:
    name: libvirtd
    enabled: true
    state: started

- ansible.builtin.include_role:
    name: linux-system-roles.tuned
  vars:
    profile: virtual-host
