- name: Install libvirt related packages
  ansible.builtin.dnf:
    name:
      - libvirt-daemon-kvm
      - tuned
    state: latest

- name: Enable libvirt daemon
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Get current tuned profile
  command: tuned-adm active
  register: profile
  changed_when: false

- debug: msg="{{ profile }}"

- name: Set tuned profile to virtual-host
  command: tuned-adm profile virtual-host
  when: profile.stdout != "Current active profile: virtual-host"
